openapi: 3.0.0
info:
  title: Vocabverse API
  version: 1.0.0
paths:
  /:
    get:
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: The dictionary term to query
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        "302":
          description: Redirect
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
